'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Ban, CircleDollarSign, Download, ListPlus, Pencil, Plus } from 'lucide-react';
import { getSupabase } from '@/lib/supabase';
import type { CurrentIdentity } from '@/lib/session';
import type { Patient, TeamMember } from '@/lib/types';
import { Empty, Modal, PageHead } from './ui';

type WaitRow={id:string;patient_id:string;service_name:string;preferred_time:string|null;priority:number;status:string;notes:string|null;patient?:{first_name:string;last_name:string}|null;staff?:{full_name:string}|null};
type Payment={id:string;amount:number;currency:string;method:string;status:string;paid_at:string|null;created_at:string;patient?:{first_name:string;last_name:string}|null};
type Block={id:string;starts_at:string;ends_at:string;reason:string;all_day:boolean;staff?:{full_name:string}|null};
type ChangeRequest={id:string;request_type:string;preferred_text:string|null;status:string;created_at:string;patient?:{first_name:string;last_name:string}|null;appointment?:{starts_at:string;service_name:string}|null};
type BookingRequest={id:string;service_name:string;preferred_text:string;status:string;created_at:string;patient?:{first_name:string;last_name:string}|null;staff?:{full_name:string}|null};
type Tab='requests'|'waitlist'|'payments'|'blocks'|'reports';

export function OperationsModule({identity,notify}:{identity:CurrentIdentity;notify:(t:string)=>void}){
  if(identity.kind!=='staff')return null;
  const member=identity.member;
  const canAdmin=['super_admin','admin_professional','secretary'].includes(member.role);
  const [tab,setTab]=useState<Tab>(canAdmin?'requests':'waitlist');
  const [patients,setPatients]=useState<Patient[]>([]);const [team,setTeam]=useState<TeamMember[]>([]);
  const [requests,setRequests]=useState<ChangeRequest[]>([]);const [bookingRequests,setBookingRequests]=useState<BookingRequest[]>([]);const [waitlist,setWaitlist]=useState<WaitRow[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [blocks,setBlocks]=useState<Block[]>([]);
  const [modal,setModal]=useState<'wait'|'payment'|'block'|null>(null);
  const [waitForm,setWaitForm]=useState({patient_id:'',preferred_staff_id:'',service_name:'Psicología',preferred_time:'',priority:2,notes:''});
  const [payForm,setPayForm]=useState({patient_id:'',amount:'',method:'Transferencia',status:'paid',receipt_number:'',notes:''});
  const [blockForm,setBlockForm]=useState({staff_id:member.id,date:'',start:'09:00',end:'10:00',reason:'',all_day:false});

  async function load(){const s=getSupabase();const [p,t,rq,br,w,pay,b]=await Promise.all([s.from('patients').select('*').eq('active',true).order('last_name'),s.from('team_members').select('*').eq('active',true).neq('role','secretary').order('full_name'),canAdmin?s.from('appointment_change_requests').select('*,patient:patients(first_name,last_name),appointment:appointments(starts_at,service_name)').eq('status','pending').order('created_at'):Promise.resolve({data:[]}),canAdmin?s.from('appointment_requests').select('*,patient:patients(first_name,last_name),staff:team_members(full_name)').eq('status','pending').order('created_at'):Promise.resolve({data:[]}),s.from('waitlist').select('*,patient:patients(first_name,last_name),staff:team_members(full_name)').order('priority').order('created_at'),s.from('payments').select('*,patient:patients(first_name,last_name)').order('created_at',{ascending:false}).limit(200),s.from('availability_blocks').select('*,staff:team_members(full_name)').gte('ends_at',new Date().toISOString()).order('starts_at')]);setPatients((p.data||[]) as Patient[]);setTeam((t.data||[]) as TeamMember[]);setRequests((rq.data||[]) as unknown as ChangeRequest[]);setBookingRequests((br.data||[]) as unknown as BookingRequest[]);setWaitlist((w.data||[]) as unknown as WaitRow[]);setPayments((pay.data||[]) as unknown as Payment[]);setBlocks((b.data||[]) as unknown as Block[])}
  useEffect(()=>{load()},[]);
  async function updateRequest(id:string,status:string){const r=await getSupabase().from('appointment_change_requests').update({status,reviewed_by:member.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(r.error)notify(r.error.message);else{notify('Solicitud actualizada.');load()}}
  async function updateBookingRequest(id:string,status:string){const r=await getSupabase().from('appointment_requests').update({status,reviewed_by:member.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(r.error)notify(r.error.message);else{notify('Solicitud de turno actualizada.');load()}}
  async function addWait(e:FormEvent){e.preventDefault();const r=await getSupabase().from('waitlist').insert({...waitForm,preferred_staff_id:waitForm.preferred_staff_id||null,preferred_time:waitForm.preferred_time||null,notes:waitForm.notes||null});if(r.error)return notify(r.error.message);setModal(null);notify('Paciente agregado a la lista de espera.');load()}
  async function updateWait(id:string,status:string){const r=await getSupabase().from('waitlist').update({status}).eq('id',id);if(r.error)notify(r.error.message);else{notify('Lista de espera actualizada.');load()}}
  async function addPayment(e:FormEvent){e.preventDefault();const r=await getSupabase().from('payments').insert({patient_id:payForm.patient_id,amount:Number(payForm.amount),method:payForm.method,status:payForm.status,receipt_number:payForm.receipt_number||null,notes:payForm.notes||null,paid_at:payForm.status==='paid'?new Date().toISOString():null});if(r.error)return notify(r.error.message);setModal(null);notify('Movimiento de caja registrado.');load()}
  async function addBlock(e:FormEvent){e.preventDefault();const start=new Date(`${blockForm.date}T${blockForm.all_day?'00:00':blockForm.start}:00`);const end=new Date(`${blockForm.date}T${blockForm.all_day?'23:59':blockForm.end}:00`);const r=await getSupabase().from('availability_blocks').insert({staff_id:blockForm.staff_id,starts_at:start.toISOString(),ends_at:end.toISOString(),reason:blockForm.reason,all_day:blockForm.all_day});if(r.error)return notify(r.error.message);setModal(null);notify('Bloqueo de agenda creado.');load()}
  async function exportCsv(){const s=getSupabase();const r=await s.from('appointments').select('starts_at,duration_minutes,service_name,modality,status,patient:patients(first_name,last_name),staff:team_members(full_name)').order('starts_at',{ascending:false}).limit(5000);if(r.error)return notify(r.error.message);const rows=[['Fecha','Hora','Paciente','Profesional','Servicio','Duración','Modalidad','Estado'],...(r.data||[]).map((a:any)=>{const d=new Date(a.starts_at);return[d.toLocaleDateString('es-AR'),d.toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'}),`${a.patient?.first_name||''} ${a.patient?.last_name||''}`,a.staff?.full_name||'',a.service_name,String(a.duration_minutes),a.modality,a.status]})];const csv=rows.map(row=>row.map((v: unknown)=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([`\uFEFF${csv}`],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`turnos-meriggi-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);notify('Reporte exportado.')}
  const paid=payments.filter(p=>p.status==='paid').reduce((sum,p)=>sum+Number(p.amount),0);const pending=payments.filter(p=>p.status==='pending').reduce((sum,p)=>sum+Number(p.amount),0);
  return <section className="page"><PageHead eyebrow="Gestión operativa" title="Operaciones" description="Lista de espera, caja, bloqueos de agenda y reportes exportables."/><div className="toolbar">{canAdmin&&<button className={`btn ${tab==='requests'?'primary':''}`} onClick={()=>setTab('requests')}><Pencil size={16}/> Solicitudes</button>}<button className={`btn ${tab==='waitlist'?'primary':''}`} onClick={()=>setTab('waitlist')}><ListPlus size={16}/> Lista de espera</button>{canAdmin&&<button className={`btn ${tab==='payments'?'primary':''}`} onClick={()=>setTab('payments')}><CircleDollarSign size={16}/> Caja</button>}<button className={`btn ${tab==='blocks'?'primary':''}`} onClick={()=>setTab('blocks')}><Ban size={16}/> Bloqueos</button><button className={`btn ${tab==='reports'?'primary':''}`} onClick={()=>setTab('reports')}><Download size={16}/> Reportes</button></div>
  {tab==='requests'&&<div className="grid" style={{gap:16}}><article className="card table-wrap"><div className="card-head" style={{padding:'20px 20px 0'}}><div><span className="eyebrow">Portal de pacientes</span><h2>Solicitudes de nuevos turnos</h2></div><span className="pill">{bookingRequests.length} pendientes</span></div>{bookingRequests.length===0?<Empty title="Sin solicitudes nuevas" text="Las solicitudes de nuevos turnos aparecerán aquí cuando la autogestión esté habilitada."/>:<table><thead><tr><th>Paciente</th><th>Servicio</th><th>Preferencias</th><th>Fecha</th><th>Resolver</th></tr></thead><tbody>{bookingRequests.map(r=><tr key={r.id}><td>{r.patient?`${r.patient.first_name} ${r.patient.last_name}`:'Paciente'}</td><td>{r.service_name}</td><td>{r.preferred_text}</td><td>{new Date(r.created_at).toLocaleString('es-AR')}</td><td><div className="actions"><button className="btn small" onClick={()=>updateBookingRequest(r.id,'approved')}>Aprobar</button><button className="btn small danger" onClick={()=>updateBookingRequest(r.id,'rejected')}>Rechazar</button></div></td></tr>)}</tbody></table>}</article><article className="card table-wrap"><div className="card-head" style={{padding:'20px 20px 0'}}><div><span className="eyebrow">Turnos existentes</span><h2>Solicitudes de reprogramación</h2></div><span className="pill">{requests.length} pendientes</span></div>{requests.length===0?<Empty title="Sin reprogramaciones pendientes" text="Las solicitudes de cambio de turnos aparecerán aquí."/>:<table><thead><tr><th>Paciente</th><th>Turno actual</th><th>Solicitud</th><th>Fecha</th><th>Resolver</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.patient?`${r.patient.first_name} ${r.patient.last_name}`:'Paciente'}</td><td>{r.appointment?`${new Date(r.appointment.starts_at).toLocaleString('es-AR')} · ${r.appointment.service_name}`:'Turno'}</td><td>{r.preferred_text||r.request_type}</td><td>{new Date(r.created_at).toLocaleString('es-AR')}</td><td><div className="actions"><button className="btn small" onClick={()=>updateRequest(r.id,'approved')}>Aprobar</button><button className="btn small danger" onClick={()=>updateRequest(r.id,'rejected')}>Rechazar</button></div></td></tr>)}</tbody></table>}</article></div>}
  {tab==='waitlist'&&<article className="card table-wrap"><div className="card-head" style={{padding:'20px 20px 0'}}><div><span className="eyebrow">Demanda pendiente</span><h2>Lista de espera</h2></div>{canAdmin&&<button className="btn primary" onClick={()=>setModal('wait')}><Plus size={16}/> Agregar</button>}</div>{waitlist.length===0?<Empty title="Lista vacía" text="No hay pacientes esperando disponibilidad."/>:<table><thead><tr><th>Paciente</th><th>Servicio</th><th>Preferencia</th><th>Prioridad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{waitlist.map(w=><tr key={w.id}><td><strong>{w.patient?`${w.patient.first_name} ${w.patient.last_name}`:'Paciente'}</strong><small>{w.staff?.full_name||'Cualquier profesional'}</small></td><td>{w.service_name}</td><td>{w.preferred_time||'Sin preferencia'}<small>{w.notes||''}</small></td><td><span className={`pill ${w.priority===1?'bad':w.priority===3?'blue':''}`}>{w.priority===1?'Alta':w.priority===2?'Media':'Baja'}</span></td><td>{w.status}</td><td>{canAdmin&&<select className="select" value={w.status} onChange={e=>updateWait(w.id,e.target.value)}><option value="waiting">En espera</option><option value="offered">Turno ofrecido</option><option value="scheduled">Agendado</option><option value="closed">Cerrado</option></select>}</td></tr>)}</tbody></table>}</article>}
  {tab==='payments'&&<><div className="grid stats"><article className="card stat"><span>Cobrado</span><strong>${paid.toLocaleString('es-AR')}</strong><small>Movimientos pagados</small></article><article className="card stat"><span>Pendiente</span><strong>${pending.toLocaleString('es-AR')}</strong><small>Saldo registrado</small></article><article className="card stat"><span>Movimientos</span><strong>{payments.length}</strong><small>Últimos 200</small></article><article className="card stat"><span>Moneda</span><strong>ARS</strong><small>Configuración inicial</small></article></div><article className="card table-wrap"><div className="card-head" style={{padding:'20px 20px 0'}}><div><span className="eyebrow">Administración</span><h2>Caja y pagos</h2></div>{canAdmin&&<button className="btn primary" onClick={()=>setModal('payment')}><Plus size={16}/> Registrar pago</button>}</div>{payments.length===0?<Empty title="Sin movimientos" text="Los pagos y saldos aparecerán aquí."/>:<table><thead><tr><th>Fecha</th><th>Paciente</th><th>Importe</th><th>Método</th><th>Estado</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{new Date(p.paid_at||p.created_at).toLocaleDateString('es-AR')}</td><td>{p.patient?`${p.patient.first_name} ${p.patient.last_name}`:'Paciente'}</td><td><strong>${Number(p.amount).toLocaleString('es-AR')}</strong></td><td>{p.method}</td><td><span className={`pill ${p.status==='paid'?'ok':p.status==='refunded'?'bad':''}`}>{p.status}</span></td></tr>)}</tbody></table>}</article></>}
  {tab==='blocks'&&<article className="card table-wrap"><div className="card-head" style={{padding:'20px 20px 0'}}><div><span className="eyebrow">Disponibilidad</span><h2>Bloqueos de agenda</h2></div><button className="btn primary" onClick={()=>setModal('block')}><Plus size={16}/> Nuevo bloqueo</button></div>{blocks.length===0?<Empty title="Sin bloqueos próximos" text="Vacaciones, licencias y reuniones aparecerán aquí."/>:<table><thead><tr><th>Profesional</th><th>Desde</th><th>Hasta</th><th>Motivo</th></tr></thead><tbody>{blocks.map(b=><tr key={b.id}><td>{b.staff?.full_name||'Profesional'}</td><td>{new Date(b.starts_at).toLocaleString('es-AR')}</td><td>{new Date(b.ends_at).toLocaleString('es-AR')}</td><td>{b.reason}</td></tr>)}</tbody></table>}</article>}
  {tab==='reports'&&<div className="grid two"><article className="card"><span className="eyebrow">Exportación</span><h2>Turnos y asistencia</h2><p>Descargá hasta 5.000 turnos visibles para tu usuario en formato CSV, compatible con Excel y Google Sheets.</p><button className="btn primary" onClick={exportCsv}><Download size={16}/> Exportar turnos</button></article><article className="card"><span className="eyebrow">Indicadores</span><h2>Resumen operativo</h2><div className="quick-list"><div className="quick-item"><strong>{waitlist.filter(w=>w.status==='waiting').length} personas en lista de espera</strong></div><div className="quick-item"><strong>{blocks.length} bloqueos próximos</strong></div><div className="quick-item"><strong>{payments.length} movimientos de caja visibles</strong></div></div></article></div>}
  {modal==='wait'&&<Modal title="Agregar a lista de espera" onClose={()=>setModal(null)}><form onSubmit={addWait}><div className="form-grid"><label className="field">Paciente<select className="select" value={waitForm.patient_id} onChange={e=>setWaitForm({...waitForm,patient_id:e.target.value})} required><option value="">Seleccionar…</option>{patients.map(p=><option key={p.id} value={p.id}>{p.last_name}, {p.first_name}</option>)}</select></label><label className="field">Profesional preferido<select className="select" value={waitForm.preferred_staff_id} onChange={e=>setWaitForm({...waitForm,preferred_staff_id:e.target.value})}><option value="">Cualquiera</option>{team.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label className="field">Servicio<input className="input" value={waitForm.service_name} onChange={e=>setWaitForm({...waitForm,service_name:e.target.value})}/></label><label className="field">Preferencia horaria<input className="input" placeholder="Ej.: martes por la tarde" value={waitForm.preferred_time} onChange={e=>setWaitForm({...waitForm,preferred_time:e.target.value})}/></label><label className="field">Prioridad<select className="select" value={waitForm.priority} onChange={e=>setWaitForm({...waitForm,priority:+e.target.value})}><option value={1}>Alta</option><option value={2}>Media</option><option value={3}>Baja</option></select></label><label className="field full">Notas<textarea className="textarea" value={waitForm.notes} onChange={e=>setWaitForm({...waitForm,notes:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setModal(null)}>Cancelar</button><button className="btn primary">Guardar</button></div></form></Modal>}
  {modal==='payment'&&<Modal title="Registrar movimiento" onClose={()=>setModal(null)}><form onSubmit={addPayment}><div className="form-grid"><label className="field">Paciente<select className="select" value={payForm.patient_id} onChange={e=>setPayForm({...payForm,patient_id:e.target.value})} required><option value="">Seleccionar…</option>{patients.map(p=><option key={p.id} value={p.id}>{p.last_name}, {p.first_name}</option>)}</select></label><label className="field">Importe<input className="input" type="number" min="0" step="0.01" value={payForm.amount} onChange={e=>setPayForm({...payForm,amount:e.target.value})} required/></label><label className="field">Método<select className="select" value={payForm.method} onChange={e=>setPayForm({...payForm,method:e.target.value})}><option>Transferencia</option><option>Efectivo</option><option>Tarjeta</option><option>Obra social</option><option>Otro</option></select></label><label className="field">Estado<select className="select" value={payForm.status} onChange={e=>setPayForm({...payForm,status:e.target.value})}><option value="paid">Pagado</option><option value="pending">Pendiente</option><option value="waived">Bonificado</option><option value="refunded">Reintegrado</option></select></label><label className="field">Comprobante<input className="input" value={payForm.receipt_number} onChange={e=>setPayForm({...payForm,receipt_number:e.target.value})}/></label><label className="field full">Notas<textarea className="textarea" value={payForm.notes} onChange={e=>setPayForm({...payForm,notes:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setModal(null)}>Cancelar</button><button className="btn primary">Registrar</button></div></form></Modal>}
  {modal==='block'&&<Modal title="Bloquear agenda" onClose={()=>setModal(null)}><form onSubmit={addBlock}><div className="form-grid"><label className="field">Profesional<select className="select" value={blockForm.staff_id} disabled={member.role==='professional'} onChange={e=>setBlockForm({...blockForm,staff_id:e.target.value})}>{team.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label className="field">Fecha<input className="input" type="date" value={blockForm.date} onChange={e=>setBlockForm({...blockForm,date:e.target.value})} required/></label><label className="field">Desde<input className="input" type="time" disabled={blockForm.all_day} value={blockForm.start} onChange={e=>setBlockForm({...blockForm,start:e.target.value})}/></label><label className="field">Hasta<input className="input" type="time" disabled={blockForm.all_day} value={blockForm.end} onChange={e=>setBlockForm({...blockForm,end:e.target.value})}/></label><label className="field full"><input type="checkbox" checked={blockForm.all_day} onChange={e=>setBlockForm({...blockForm,all_day:e.target.checked})}/> Día completo</label><label className="field full">Motivo<input className="input" value={blockForm.reason} onChange={e=>setBlockForm({...blockForm,reason:e.target.value})} required/></label></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setModal(null)}>Cancelar</button><button className="btn primary">Crear bloqueo</button></div></form></Modal>}
  </section>
}
